### ISSUE TITLE
[FEATURE] migration to next.js

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#114]
### Description

use next.js for supporting open graph

### Todos

- [x] initialize project with next.js 13
- [x] routing based file system
- [x] use i18next
- [ ] migrate other files...

### ETC

* use tailwind
* next.js 13 with app router
* storybook
* use svgr (svg into react component)
* i18n support
* use lottie animation (rather than *.gif)
