### ISSUE TITLE
[FEATURE] Build Compositions

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#14]
### Description

Build these composition items (in below list)

### Todos

- [ ]  메인페이지에서 자보 묶는 것 + 좌우 스크롤 : ZaboCarousel
- [ ]  검색 아이템 컴포넌트 (사진 있는 것) : SearchResult
- [ ]  검색 아이템 컴포넌트 (사진 없는 것) : SearchResultText
- [ ]  Navbar
- [ ]  Footer
- [ ]  공지글 테이블 컴포넌트 (학사 공지) : AcademicTable

### ETC

Font "Noto Sans KR" is not working; ill try to fix it
