### ISSUE TITLE
[FEATURE] Change Notice Detail page to v3 design

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#235]
### Description

공지 상세 페이지를 v3 디자인으로 옮깁니다. 

### Todos

- [ ] only text notice view
- [ ] notice with pictures view
- [ ] build label button component
- [ ] build additional notice component
- [ ] handle mobile view
