### ISSUE TITLE
[FEATURE] Add Detailed Notice Page

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#26]
### Description

공지 상세 페이지 추가하기
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/dbbe0d05-894e-468c-9658-54c0fd3bf04e)

### Todos

- [x] Build the page UI
- [x] Build Lazy-loading zabo component 

**BugFix**
- [x] Box-shadow -> Border + Border-box
- [x] FilledArrowBtn.tsx -> Switch 문을 AnimatedBtn 안으로
- [x] tGP와 tMS를 직관적인 이름으로 바꾸기

**Refactor**
- [x] Animation 관련 컴포넌트 - 재사용 없으므로 줄이기
- [x] FilledArrow 

### ETC

무한스크롤 되는 컴포넌트는 어떻게 처리하여야 할지 감이 잡히지 않는데
일단 해당 컴포넌트도 이 페이지 개발하는 겸 같이 개발해보겠습니다

**Comment by 2paperstar** [comment]
무한스크롤 되는 컴포넌트:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout
https://drafts.csswg.org/css-grid-3/#masonry-layout
이..런게 있긴한데 아직 level 3를 지원하는게 firefox밖에 없다네요 ㅜㅜ

하지만! 이미 좋은 리액트 라이브러리가 존재하죠
https://www.npmjs.com/package/react-responsive-masonry
