### ISSUE TITLE
[FEATURE] Add Navigations and connect APIs

### ISSUE THREAD

**Issue by dohyun-ko** [gsainfoteam/ziggle-fe#31]
### Description

페이지간 네비게이션을 추가하고 API를 연결합니다.

### Todos

- [x] 네비게이션 추가
- [ ] Tag API 연결
- [x] Notice API 연결
- [ ] Image API 연결
