### ISSUE TITLE
[FEATURE] fix notice writing and tag bug

### ISSUE THREAD

**Issue by dohyun-ko** [gsainfoteam/ziggle-fe#44]
### Description

공지 작성 API 연결 불완전
태그 생성 api 작동하지 않음
추가로 보성이가 언급한 수정사항들 반영

### Todos

- [x] 공지 작성 로직
- [x] 태그 생성 로직
- [x] 보성이가 말한 수정사항들 적용
