### ISSUE TITLE
[BUGFIX] FIx Various UI Bugs

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#55]
### Description

잡다한 UI 버그를 고친다.
마이페이지 에서 글 삭제 기능을 추가한다.
자기가 작성했거나 리마인드 표시한 모든 공지를 볼 수 있게 한다.

### Todos

- [x] Banner Navigation
- [x] Banner에 공지 작성 링킹
- [x] ZaboCarousel에 내용 들어오지 않을 시 없다고 표시
- [x] TextZabo 가독성있게 만들기
- [x] TextZabo 미리보기 표시
- [x] ZaboCarousel에 표시되는 자보 수 제한 (10)
- [x] SearchResult 이상하게 나오는 버그 수정
- [x] 학사공지 게시판 링킹
- [x] 지스트 링크 변경
